---

- name: Configure horde
  block:
    - name: Setup horde support files
      ansible.builtin.copy:
        content: "{{ horde_file.content }}"
        dest: "{{ horde_file.file }}"
        owner: "{{ horde_file.owner | d(horde_default_owner) }}"
        group: "{{ horde_file.group | d(horde_default_group) }}"
        mode: "{{ horde_file.mode | d(horde_default_mode) }}"
      loop: >-
        {{ horde_files
           | selectattr("file", "defined")
           | selectattr("state", "defined")
           | selectattr("state", "equalto", "present")
           | list }}
      loop_control:
        loop_var: horde_file
        label: "{{ horde_file.file }}"

    - name: Remove horde support files
      ansible.builtin.file:
        path: "{{ horde_file.file }}"
        state: absent
      loop: >-
        {{ horde_files
           | selectattr("file", "defined")
           | selectattr("state", "defined")
           | selectattr("state", "equalto", "absent")
           | list }}
      loop_control:
        loop_var: horde_file
        label: "{{ horde_file.file }}"

  tags:
    - role::horde
    - role::horde::configure
