---

- name: Install horde
  include_tasks: install.yml
  tags:
    - role::horde
    - role::horde::install

- name: Configure horde
  include_tasks: configure.yml
  tags:
    - role::horde
    - role::horde::configure
