---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
    requirements-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
driver:
  name: docker
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:centos7
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:stream8
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          horde_files:
            - file: "{{ horde_config_dir }}/prefs.local.php"
              description: "Custom preferences"
              state: present
              content: |
                <?php
                  $_prefs['from_addr']['hook'] = true;
                  $_prefs['from_addr']['locked'] = true;
                  $_prefs['fullname']['hook'] = true;
                  $_prefs['fullname']['locked'] = true;
                  $_prefs['id']['hook'] = true;
                  $_prefs['id']['locked'] = true;
                  $_prefs['initial_application']['value'] = 'imp';
                  $_prefs['initial_application']['locked'] = true;
                  $_prefs['first_week_day']['value'] = '1';
                  $_prefs['default_identity']['locked'] = 1;
                  $_prefs['theme']['value'] = 'my_theme';
                  $_prefs['theme']['locked'] = true;
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
